{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPcxVasz9yoxqVQKHJRmbi/"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "os.environ[\"YFINANCE_USE_CURL\"] = \"False\"\n",
        "\n",
        "import yfinance as yf\n",
        "import pandas as pd\n",
        "\n",
        "# =========================\n",
        "# 📊 RSI FUNCTION\n",
        "# =========================\n",
        "def calculate_rsi(data, window=14):\n",
        "    delta = data['Close'].diff()\n",
        "    gain = delta.clip(lower=0).rolling(window).mean()\n",
        "    loss = -delta.clip(upper=0).rolling(window).mean()\n",
        "    rs = gain / loss\n",
        "    return 100 - (100 / (1 + rs))\n",
        "\n",
        "# =========================\n",
        "# 📊 SUPPORT LEVEL\n",
        "# =========================\n",
        "def get_support_level(data):\n",
        "    return float(data['Low'].tail(20).min())\n",
        "\n",
        "# =========================\n",
        "# 🎯 TARGET & STOPLOSS\n",
        "# =========================\n",
        "def calculate_target_stoploss(price, support):\n",
        "    stop_loss = support * 0.98\n",
        "    risk = price - support\n",
        "    target = price + (2 * risk)\n",
        "    return round(target, 2), round(stop_loss, 2)\n",
        "\n",
        "# =========================\n",
        "# 🎯 SIGNAL LOGIC\n",
        "# =========================\n",
        "def generate_signal(curr):\n",
        "    sma50 = curr['SMA50'].item()\n",
        "    sma200 = curr['SMA200'].item()\n",
        "    rsi = curr['RSI'].item()\n",
        "\n",
        "    if sma50 > sma200 and rsi < 70:\n",
        "        return \"🟢 BUY\"\n",
        "    elif sma50 < sma200 and rsi > 40:\n",
        "        return \"🔴 SELL\"\n",
        "    else:\n",
        "        return \"🟡 HOLD\"\n",
        "\n",
        "# =========================\n",
        "# 📊 FETCH DATA\n",
        "# =========================\n",
        "def fetch_data(ticker):\n",
        "    try:\n",
        "        data = yf.download(\n",
        "            ticker,\n",
        "            period=\"1y\",\n",
        "            interval=\"1d\",\n",
        "            progress=False,\n",
        "            auto_adjust=True\n",
        "        )\n",
        "        if data is None or data.empty:\n",
        "            return None\n",
        "        return data\n",
        "    except:\n",
        "        return None\n",
        "\n",
        "# =========================\n",
        "# 📊 MARKET RETURN\n",
        "# =========================\n",
        "def calculate_market_return(nifty, buy_date):\n",
        "    try:\n",
        "        start_price = nifty[nifty.index >= buy_date].iloc[0]['Close'].item()\n",
        "        current_price = nifty.iloc[-1]['Close'].item()\n",
        "        return ((current_price - start_price) / start_price) * 100\n",
        "    except:\n",
        "        return None\n",
        "\n",
        "# =========================\n",
        "# 🚀 MAIN ANALYSIS\n",
        "# =========================\n",
        "def analyze_stock():\n",
        "\n",
        "    # 🔹 USER INPUT\n",
        "    stock = input(\"Enter Stock (e.g. RELIANCE.NS): \").upper()\n",
        "    buy_price = float(input(\"Enter Your Buying Price: \"))\n",
        "    buy_date = input(\"Enter Buying Date (YYYY-MM-DD): \")\n",
        "\n",
        "    print(f\"\\nFetching data for {stock}...\")\n",
        "\n",
        "    # 📥 STOCK DATA\n",
        "    data = fetch_data(stock)\n",
        "\n",
        "    if data is None:\n",
        "        print(f\"❌ No data found for {stock}\")\n",
        "        print(\"👉 Example: HDFCBANK.NS instead of HDFC.NS\")\n",
        "        return\n",
        "\n",
        "    # 📥 MARKET DATA\n",
        "    nifty = fetch_data(\"^NSEI\")\n",
        "\n",
        "    # 📊 INDICATORS\n",
        "    data['SMA50'] = data['Close'].rolling(50).mean()\n",
        "    data['SMA200'] = data['Close'].rolling(200).mean()\n",
        "    data['RSI'] = calculate_rsi(data)\n",
        "\n",
        "    data = data.dropna()\n",
        "\n",
        "    if len(data) == 0:\n",
        "        print(\"❌ Not enough data\")\n",
        "        return\n",
        "\n",
        "    latest = data.iloc[-1]\n",
        "\n",
        "    # 📈 RETURNS\n",
        "    current_price = latest['Close'].item()\n",
        "    stock_return = ((current_price - buy_price) / buy_price) * 100\n",
        "\n",
        "    # 📈 MARKET RETURN\n",
        "    if nifty is not None:\n",
        "        market_return = calculate_market_return(nifty, buy_date)\n",
        "    else:\n",
        "        market_return = None\n",
        "\n",
        "    # 📊 SUPPORT\n",
        "    support = get_support_level(data)\n",
        "\n",
        "    # 🎯 TARGET & STOPLOSS\n",
        "    target, stop_loss = calculate_target_stoploss(current_price, support)\n",
        "\n",
        "    # 🎯 SIGNAL\n",
        "    signal = generate_signal(latest)\n",
        "\n",
        "    # =========================\n",
        "    # 📊 OUTPUT\n",
        "    # =========================\n",
        "    print(\"\\n📊 ANALYSIS RESULT\")\n",
        "    print(\"=\" * 40)\n",
        "    print(f\"Stock: {stock}\")\n",
        "    print(f\"Current Price: {round(current_price, 2)}\")\n",
        "    print(f\"Your Return: {round(stock_return, 2)}%\")\n",
        "\n",
        "    if market_return is not None:\n",
        "        print(f\"Market Return (NIFTY): {round(market_return, 2)}%\")\n",
        "    else:\n",
        "        print(\"Market Return: Not available\")\n",
        "\n",
        "    print(f\"RSI: {round(latest['RSI'].item(), 2)}\")\n",
        "    print(f\"SMA50: {round(latest['SMA50'].item(), 2)}\")\n",
        "    print(f\"SMA200: {round(latest['SMA200'].item(), 2)}\")\n",
        "    print(f\"Support Level: {support}\")\n",
        "    print(f\"Target Price: {target}\")\n",
        "    print(f\"Stop Loss: {stop_loss}\")\n",
        "    print(f\"Signal: {signal}\")\n",
        "\n",
        "    # =========================\n",
        "    # 💡 SUGGESTION\n",
        "    # =========================\n",
        "    print(\"\\n💡 SUGGESTION:\")\n",
        "\n",
        "    if signal == \"🟢 BUY\":\n",
        "        print(f\"Strong stock. Target: {target}, Stop Loss: {stop_loss}\")\n",
        "\n",
        "    elif signal == \"🔴 SELL\":\n",
        "        print(\"Weak trend. Consider exiting or reducing position.\")\n",
        "\n",
        "    else:\n",
        "        if latest['RSI'].item() < 35:\n",
        "            print(f\"Oversold zone. Possible bounce.\\nTarget: {target}, Stop Loss: {stop_loss}\")\n",
        "        else:\n",
        "            print(\"Hold and wait for better opportunity.\")\n",
        "\n",
        "# =========================\n",
        "# ▶️ RUN\n",
        "# =========================\n",
        "if __name__ == \"__main__\":\n",
        "    analyze_stock()\n"
      ],
      "metadata": {
        "id": "SIgK5u0d-JyK"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}